<option value="62">印度尼西亚</option>
<option value="60">马来西亚</option>
<option value="65">新加坡</option>
<option value="81">日本</option>
<option value="82">韩国</option>
<option value="852">香港</option>
<option value="853">澳门</option>
<option value="86">中国</option>
<option value="91">印度</option>
<option value="376">Andorra 安道尔</option>
<option value="971">Arab Emirates</option>
<option value="">Afghanistan 阿富汗</option>
<option value="355">Albania</option>
<option value="374">Armenia</option>
<option value="599">NETHERLANDS ANTILLES</option>
<option value="244">Angola</option>
<option value="54">Argentina</option>
<option value="43">austria</option>
<option value="61">澳大利亚</option>
<option value="297">Aruba</option>
<option value="994">Azerbaijan</option>
<option value="387">Bosnia and Herzegovina</option>
<option value="880">Bangladesh</option>
<option value="32">Belgium</option>
<option value="226">BurkinaFaso</option>
<option value="359">Bulgaria</option>
<option value="973">Bahrain</option>
<option value="257">Burundi</option>
<option value="229">Benin</option>
<option value="673">Brunei Darussalam</option>
<option value="591">Bolivia</option>
<option value="55">巴西</option>
<option value="975">Bhutan</option>
<option value="267">Botswana</option>
<option value="375">Belarus</option>
<option value="501">Belize</option>
<option value="1">加拿大</option>
<option value="243">Democratic Republic of the Congo</option>
<option value="236">Central African Republic</option>
<option value="242">Congo</option>
<option value="41">瑞士</option>
<option value="225">Cote d'Ivoire</option>
<option value="682">Cook Islands</option>
<option value="56">Chile</option>
<option value="237">Cameroon</option>
<option value="86">中国</option>
<option value="57">Colombia</option>
<option value="506">CostaRica</option>
<option value="53">Cuba</option>
<option value="238">Cape Verde</option>
<option value="357">Cyprus</option>
<option value="420">Czech Republic</option>
<option value="49">德国</option>
<option value="253">Djibouti</option>
<option value="45">丹麦</option>
<option value="213">Algeria</option>
<option value="593">Ecuador</option>
<option value="372">Estonia</option>
<option value="20">埃及</option>
<option value="">Western Sahara</option>
<option value="291">Eritrea</option>
<option value="34">西班牙</option>
<option value="251">Ethiopia</option>
<option value="358">芬兰</option>
<option value="679">Fiji</option>
<option value="500">Falkland Islands</option>
<option value="">Manicronesia</option>
<option value="298">Faroe Islands</option>
<option value="33">法国</option>
<option value="241">Gabon</option>
<option value="44">英国</option>
<option value="995">Georgia</option>
<option value="594">French Guiana</option>
<option value="233">Ghana</option>
<option value="350">Gibraltar</option>
<option value="299">Greenland</option>
<option value="220">The Gambia</option>
<option value="224">Guinea</option>
<option value="590">Guadeloupe</option>
<option value="30">希腊</option>
<option value="995">South Georgia and the South Sandwich Islands</option>
<option value="502">Guatemala</option>
<option value="245">Guinea-Bissau</option>
<option value="592">Guyana</option>
<option value="852">香港</option>
<option value="504">Honduras</option>
<option value="385">Croatia</option>
<option value="509">Haiti</option>
<option value="36">匈牙利</option>
<option value="62">印度尼西亚</option>
<option value="353">Ireland</option>
<option value="972">以色列</option>
<option value="91">印度</option>
<option value="964">Iraq</option>
<option value="98">Iran</option>
<option value="354">Iceland</option>
<option value="39">意大利</option>
<option value="962">Jordan</option>
<option value="81">日本</option>
<option value="254">Kenya</option>
<option value="996">Kyrgyzstan</option>
<option value="855">Cambodia</option>
<option value="686">Kiribati</option>
<option value="269">Comoros</option>
<option value="82">韩国</option>
<option value="965">科威特</option>
<option value="7">Kazakhstan</option>
<option value="856">Lao People s Democratic Republic</option>
<option value="961">Lebanon</option>
<option value="423">Liechtenstein</option>
<option value="94">Sri Lanka</option>
<option value="231">Liberia</option>
<option value="266">Lesotho</option>
<option value="370">Lithuania</option>
<option value="352">Luxembourg</option>
<option value="371">Latvia</option>
<option value="218">Libya</option>
<option value="212">Morocco</option>
<option value="377">Monaco</option>
<option value="373">Moldova</option>
<option value="261">Madagascar</option>
<option value="692">Marshall Islands</option>
<option value="389">Macedonia</option>
<option value="223">Mali</option>
<option value="95">缅甸</option>
<option value="976">Mongolia</option>
<option value="853">澳门</option>
<option value="596">Martinique</option>
<option value="222">Mauritania</option>
<option value="356">Malta</option>
<option value="230">Mauritius</option>
<option value="960">Maldives</option>
<option value="265">Malawi</option>
<option value="52">墨西哥</option>
<option value="60">马来西亚</option>
<option value="258">Mozambique</option>
<option value="264">Namibia</option>
<option value="687">New Caledonia</option>
<option value="227">Niger</option>
<option value="">Norfolk Island</option>
<option value="234">Nigeria</option>
<option value="505">Nicaragua</option>
<option value="31">荷兰</option>
<option value="47">挪威</option>
<option value="977">Nepal</option>
<option value="674">Nauru</option>
<option value="683">Niue</option>
<option value="64">新西兰</option>
<option value="968">Oman</option>
<option value="507">Panama</option>
<option value="51">Peru</option>
<option value="689">French Polynesia</option>
<option value="675">Papua New Guinea</option>
<option value="63">菲律宾</option>
<option value="92">Pakistan</option>
<option value="48">波兰</option>
<option value="508">Saint Pierre and Miquelon</option>
<option value="">Pitcairn Islands</option>
<option value="351">葡萄牙</option>
<option value="680">Palau</option>
<option value="595">Paraguay</option>
<option value="974">Qatar</option>
<option value="">Reunion</option>
<option value="40">Romania</option>
<option value="7">俄罗斯</option>
<option value="250">Rwanda</option>
<option value="966">Saudi Arabia</option>
<option value="677">Solomon Islands</option>
<option value="248">Seychelles</option>
<option value="249">Sudan</option>
<option value="46">瑞典</option>
<option value="65">新加坡</option>
<option value="290">Saint Helena</option>
<option value="386">Slovenia</option>
<option value="">Svalbard</option>
<option value="421">Slovakia</option>
<option value="232">Sierra Leone</option>
<option value="378">SanMarino</option>
<option value="221">Senegal</option>
<option value="252">Somalia</option>
<option value="597">Suriname</option>
<option value="239">Sao Tome and Principe</option>
<option value="503">El Salvador</option>
<option value="963">Syria</option>
<option value="268">Swaziland</option>
<option value="235">Chad</option>
<option value="228">Togo</option>
<option value="66">泰国</option>
<option value="992">Tajikistan</option>
<option value="690">Tokelau</option>
<option value="993">Turkmenistan</option>
<option value="216">Tunisia</option>
<option value="676">Tonga</option>
<option value="90">土耳其</option>
<option value="688">Tuvalu</option>
<option value="886">台湾</option>
<option value="255">Tanzania</option>
<option value="380">Ukraine</option>
<option value="256">Uganda</option>
<option value="1">美国</option>
<option value="598">Uruguay</option>
<option value="998">Uzbekistan</option>
<option value="39">Vatican</option>
<option value="58">Venezuela</option>
<option value="84">越南</option>
<option value="678">Vanuatu</option>
<option value="681">Wallis and Futuna</option>
<option value="685">Samoa</option>
<option value="">ETC</option>
<option value="967">Yemen</option>
<option value="269">Mayotte</option>
<option value="381">SERBIA AND MONTENEGRO</option>
<option value="27">South Africa</option>
<option value="260">Zambia</option>
<option value="263">Zimbabwe</option>